# Generated by Django 4.2.6 on 2023-10-30 19:23

import datetime
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_alter_course_difficulty'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Enrollment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enrolled_at', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('amount_paid', models.DecimalField(decimal_places=2, max_digits=10)),
                ('course_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.course')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Refund',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_date', models.DateTimeField(default=datetime.datetime.now)),
                ('reason', models.TextField()),
                ('status', models.CharField(max_length=50)),
                ('enrollment_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='users.enrollment')),
            ],
        ),
        migrations.CreateModel(
            name='PaymentMethod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_type', models.CharField(choices=[('visa', 'Visa'), ('mastercard', 'Mastercard'), ('debit_card', 'Debit Card')], default='visa', max_length=20, verbose_name='Payment Type')),
                ('card_number', models.CharField(max_length=16, verbose_name='Card Number')),
                ('cardholder_name', models.CharField(max_length=255, verbose_name='Cardholder Name')),
                ('expiration_month', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(12)], verbose_name='Expiration Month')),
                ('expiration_year', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(2023)], verbose_name='Expiration Year')),
                ('cvv', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(100)], verbose_name='CVV')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PaymentHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='Enrollment Date')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Amount')),
                ('status', models.CharField(max_length=50, verbose_name='Status')),
                ('enrollment_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='users.enrollment')),
                ('user_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='StudentProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_tasks', models.PositiveIntegerField()),
                ('remaining_tasks', models.PositiveIntegerField()),
                ('total_score', models.PositiveIntegerField()),
                ('enrollment_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.enrollment')),
            ],
            options={
                'indexes': [models.Index(fields=['enrollment_id'], name='users_stude_enrollm_971619_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='enrollment',
            index=models.Index(fields=['user_id', 'course_id'], name='users_enrol_user_id_ba0a21_idx'),
        ),
    ]
