# Generated by Django 4.2.6 on 2023-11-13 22:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_enrollment_payment_method_id_enrollment_refunded_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paymentmethod',
            name='cvv',
        ),
    ]
