# Generated by Django 4.2.6 on 2023-11-13 23:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_enrollment_payment_method_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentmethod',
            name='payment_type',
            field=models.CharField(max_length=20, verbose_name='Payment Type'),
        ),
    ]
