# Generated by Django 4.2.6 on 2023-10-23 19:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('courses', '0001_initial'),
        ('instructors', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='instructor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='teaching_courses', to='instructors.instructor'),
        ),
    ]
