# Generated by Django 4.2.6 on 2023-11-15 18:21

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_alter_course_difficulty'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='release_date',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now),
        ),
    ]
