# Generated by Django 4.2.6 on 2023-11-16 23:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instructors', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='instructor',
            name='mvp_month',
            field=models.DateField(blank=True, null=True),
        ),
    ]
